
// USER
export const OPEN_LOGIN_PAGE = "OPEN_LOGIN_PAGE";
export const CLOSE_LOGIN_PAGE = "CLOSE_LOGIN_PAGE";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//LAYOUT
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const TOGGLE_THEME= "TOGGLE_THEME";

//TOPMENU
export const INIT_TOP_MENU = "INIT_TOP_MENU";
export const SET_BADGET_CONTENT = "SET_BADGET_CONTENT";
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const SET_SHOW_SUBMENU_ITEMSICONS = "SET_SHOW_SUBMENU_ITEMSICONS";

//LEFTMENU
export const SET_LEFT_MENU = "SET_LEFT_MENU";